# Generated by Django 3.2.3 on 2021-05-23 13:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('NIP', models.IntegerField()),
                ('name', models.TextField()),
                ('password', models.TextField()),
                ('address', models.TextField()),
                ('phone_number', models.TextField()),
                ('domain', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('surname', models.TextField()),
                ('phone_number', models.TextField()),
                ('position', models.TextField()),
                ('address', models.TextField()),
                ('salary', models.IntegerField()),
                ('status', models.TextField(choices=[('employed', 'Currently employed'), ('discharged', 'This worker is no longer employed')])),
                ('companyID', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='manager.company')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('VIN', models.TextField(primary_key=True, serialize=False)),
                ('brand', models.TextField()),
                ('version', models.TextField()),
                ('model', models.TextField()),
                ('accessories', models.TextField()),
                ('picture', models.BinaryField()),
                ('plate_number', models.TextField()),
                ('current_mileage', models.IntegerField(default=0)),
                ('purpose', models.TextField()),
                ('distinctive_marks', models.TextField()),
                ('status', models.TextField(choices=[('operational', 'Currently operational'), ('discharged', 'This vehicle is no longer operational')])),
                ('companyID', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='manager.company')),
            ],
        ),
        migrations.CreateModel(
            name='Serviceplan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_performed', models.TextField()),
                ('mileage', models.IntegerField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('status', models.BooleanField()),
                ('accessories', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='serviceplan_accessories', to='manager.vehicle')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='serviceplan_brand', to='manager.vehicle')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='serviceplan_model', to='manager.vehicle')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='serviceplan_version', to='manager.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('work_id', models.IntegerField(primary_key=True, serialize=False)),
                ('cost', models.FloatField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('service_performed', models.TextField()),
                ('provider', models.TextField()),
                ('vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='manager.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('rent_id', models.IntegerField(primary_key=True, serialize=False)),
                ('rent_type', models.TextField(choices=[('private', 'Borrowed for private purposes'), ('buisness', 'Borrowed for buisness purposes')])),
                ('starting_mileage', models.IntegerField()),
                ('final_mileage', models.IntegerField()),
                ('exploitation_cost', models.FloatField()),
                ('costs_description', models.TextField()),
                ('rent_start', models.DateField()),
                ('rent_end', models.DateField()),
                ('rent_status', models.BooleanField(default=False)),
                ('renter_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='manager.person')),
                ('vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='manager.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(default=datetime.date.today)),
                ('date_end', models.DateField()),
                ('ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_ID', to='manager.person')),
                ('VIN', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_VIN', to='manager.vehicle')),
            ],
        ),
    ]
