# Generated by Django 3.2.3 on 2021-05-23 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manager',
            old_name='ID',
            new_name='personal_ID',
        ),
    ]
