# Generated by Django 3.2.3 on 2021-05-23 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_rename_id_manager_personal_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='VIN',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager', to='manager.vehicle'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='personal_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager', to='manager.person'),
        ),
    ]
