# Generated by Django 3.2.3 on 2021-05-24 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_alter_vehicle_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
