# Generated by Django 3.1.7 on 2021-05-24 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_alter_company_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='category',
            field=models.TextField(default='other'),
        ),
    ]
