# Generated by Django 3.2.3 on 2021-05-24 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_vehicle_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='rent_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='service',
            name='work_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
