# Generated by Django 3.1.7 on 2021-05-26 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_auto_20210524_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='login',
            field=models.TextField(default='user', unique=True),
        ),
        migrations.AddField(
            model_name='person',
            name='password',
            field=models.TextField(default='password', unique=True),
        ),
    ]
