# Generated by Django 3.2.3 on 2021-06-01 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0011_auto_20210529_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='rent_status',
            field=models.TextField(choices=[('reserved', 'Reserved for user'), ('rented', 'Rented by user'), ('given', 'Given by user')]),
        ),
    ]
