# Generated by Django 3.1.7 on 2021-06-01 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0013_auto_20210601_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='renter_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='manager.person'),
        ),
    ]
