# Generated by Django 3.1.7 on 2021-06-02 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0012_alter_rental_rent_status'),
        ('manager', '0014_auto_20210601_1255'),
    ]

    operations = [
    ]
