# Generated by Django 3.1.7 on 2021-06-02 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0015_merge_20210602_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceplan',
            name='accessories',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='serviceplan',
            name='brand',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='serviceplan',
            name='model',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='serviceplan',
            name='version',
            field=models.TextField(),
        ),
    ]
