# Generated by Django 3.1.7 on 2021-06-04 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0016_auto_20210602_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.TextField(choices=[('operational', 'Currently operational'), ('decommissioned', 'This vehicle is no longer operational')]),
        ),
    ]
