# Generated by Django 3.1.7 on 2021-06-05 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0018_alter_vehicle_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceplan',
            name='status',
        ),
        migrations.AddField(
            model_name='service',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.serviceplan'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='category',
            field=models.TextField(choices=[('sedan', 'Sedan'), ('wagon', 'Wagon'), ('hatchback', 'Hatchback'), ('van', 'Van'), ('pickup', 'Pickup'), ('truck', 'Truck'), ('construction', 'Construction'), ('agriculture', 'Agriculture'), ('storage', 'Storage'), ('other', 'Other')]),
        ),
    ]
