# Generated by Django 3.2.3 on 2021-06-05 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0019_auto_20210605_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceplan',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
