# Generated by Django 3.2.3 on 2021-06-05 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0020_alter_serviceplan_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceplan',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
